/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.screen;

/**
 *
 * @author thiag
 */

import br.com.logic.Core;

public class boardGame extends javax.swing.JFrame {
    
    int chessPiece = 0;
    int chessPieceSelected = 0;
    int x = 0;
    int y = 0;
    
    Core core = new Core();
    /**
     * Creates new form boardGame
     */
    public boardGame() {
        core.initBoard();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGame = new javax.swing.JPanel();
        bgBoard = new javax.swing.JPanel();
        p00 = new javax.swing.JPanel();
        btn00 = new javax.swing.JLabel();
        p01 = new javax.swing.JPanel();
        btn01 = new javax.swing.JLabel();
        p02 = new javax.swing.JPanel();
        btn02 = new javax.swing.JLabel();
        p03 = new javax.swing.JPanel();
        btn03 = new javax.swing.JLabel();
        p04 = new javax.swing.JPanel();
        btn04 = new javax.swing.JLabel();
        p05 = new javax.swing.JPanel();
        btn05 = new javax.swing.JLabel();
        p06 = new javax.swing.JPanel();
        btn06 = new javax.swing.JLabel();
        p07 = new javax.swing.JPanel();
        btn07 = new javax.swing.JLabel();
        p10 = new javax.swing.JPanel();
        btn10 = new javax.swing.JLabel();
        p11 = new javax.swing.JPanel();
        btn11 = new javax.swing.JLabel();
        p12 = new javax.swing.JPanel();
        btn12 = new javax.swing.JLabel();
        p13 = new javax.swing.JPanel();
        btn13 = new javax.swing.JLabel();
        p14 = new javax.swing.JPanel();
        btn14 = new javax.swing.JLabel();
        p15 = new javax.swing.JPanel();
        btn15 = new javax.swing.JLabel();
        p16 = new javax.swing.JPanel();
        btn16 = new javax.swing.JLabel();
        p17 = new javax.swing.JPanel();
        btn17 = new javax.swing.JLabel();
        p30 = new javax.swing.JPanel();
        btn30 = new javax.swing.JLabel();
        p31 = new javax.swing.JPanel();
        btn31 = new javax.swing.JLabel();
        p32 = new javax.swing.JPanel();
        btn32 = new javax.swing.JLabel();
        p33 = new javax.swing.JPanel();
        btn33 = new javax.swing.JLabel();
        p34 = new javax.swing.JPanel();
        btn34 = new javax.swing.JLabel();
        p35 = new javax.swing.JPanel();
        btn35 = new javax.swing.JLabel();
        p36 = new javax.swing.JPanel();
        btn36 = new javax.swing.JLabel();
        p37 = new javax.swing.JPanel();
        btn37 = new javax.swing.JLabel();
        p27 = new javax.swing.JPanel();
        btn27 = new javax.swing.JLabel();
        p26 = new javax.swing.JPanel();
        btn26 = new javax.swing.JLabel();
        p25 = new javax.swing.JPanel();
        btn25 = new javax.swing.JLabel();
        p24 = new javax.swing.JPanel();
        btn24 = new javax.swing.JLabel();
        p23 = new javax.swing.JPanel();
        btn23 = new javax.swing.JLabel();
        p22 = new javax.swing.JPanel();
        btn22 = new javax.swing.JLabel();
        p21 = new javax.swing.JPanel();
        btn21 = new javax.swing.JLabel();
        p20 = new javax.swing.JPanel();
        btn20 = new javax.swing.JLabel();
        p57 = new javax.swing.JPanel();
        btn57 = new javax.swing.JLabel();
        p47 = new javax.swing.JPanel();
        btn47 = new javax.swing.JLabel();
        p46 = new javax.swing.JPanel();
        btn46 = new javax.swing.JLabel();
        p45 = new javax.swing.JPanel();
        btn45 = new javax.swing.JLabel();
        p44 = new javax.swing.JPanel();
        btn44 = new javax.swing.JLabel();
        p43 = new javax.swing.JPanel();
        btn43 = new javax.swing.JLabel();
        p42 = new javax.swing.JPanel();
        btn42 = new javax.swing.JLabel();
        p41 = new javax.swing.JPanel();
        btn41 = new javax.swing.JLabel();
        p40 = new javax.swing.JPanel();
        btn40 = new javax.swing.JLabel();
        p50 = new javax.swing.JPanel();
        btn50 = new javax.swing.JLabel();
        p51 = new javax.swing.JPanel();
        btn51 = new javax.swing.JLabel();
        p52 = new javax.swing.JPanel();
        btn52 = new javax.swing.JLabel();
        p53 = new javax.swing.JPanel();
        btn53 = new javax.swing.JLabel();
        p54 = new javax.swing.JPanel();
        btn54 = new javax.swing.JLabel();
        p55 = new javax.swing.JPanel();
        btn55 = new javax.swing.JLabel();
        p56 = new javax.swing.JPanel();
        btn56 = new javax.swing.JLabel();
        p77 = new javax.swing.JPanel();
        btn77 = new javax.swing.JLabel();
        p67 = new javax.swing.JPanel();
        btn67 = new javax.swing.JLabel();
        p66 = new javax.swing.JPanel();
        btn66 = new javax.swing.JLabel();
        p65 = new javax.swing.JPanel();
        btn65 = new javax.swing.JLabel();
        p64 = new javax.swing.JPanel();
        btn64 = new javax.swing.JLabel();
        p63 = new javax.swing.JPanel();
        btn63 = new javax.swing.JLabel();
        p62 = new javax.swing.JPanel();
        btn62 = new javax.swing.JLabel();
        p61 = new javax.swing.JPanel();
        btn61 = new javax.swing.JLabel();
        p60 = new javax.swing.JPanel();
        btn60 = new javax.swing.JLabel();
        p70 = new javax.swing.JPanel();
        btn70 = new javax.swing.JLabel();
        p71 = new javax.swing.JPanel();
        btn71 = new javax.swing.JLabel();
        p72 = new javax.swing.JPanel();
        btn72 = new javax.swing.JLabel();
        p73 = new javax.swing.JPanel();
        btn73 = new javax.swing.JLabel();
        p74 = new javax.swing.JPanel();
        btn74 = new javax.swing.JLabel();
        p75 = new javax.swing.JPanel();
        btn75 = new javax.swing.JLabel();
        p76 = new javax.swing.JPanel();
        btn76 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgGame.setBackground(new java.awt.Color(245, 244, 231));

        bgBoard.setBackground(new java.awt.Color(255, 255, 255));
        bgBoard.setPreferredSize(new java.awt.Dimension(560, 560));

        p00.setBackground(new java.awt.Color(245, 244, 239));
        p00.setPreferredSize(new java.awt.Dimension(70, 70));

        btn00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_tower.png"))); // NOI18N

        javax.swing.GroupLayout p00Layout = new javax.swing.GroupLayout(p00);
        p00.setLayout(p00Layout);
        p00Layout.setHorizontalGroup(
            p00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn00, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p00Layout.setVerticalGroup(
            p00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn00, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p01.setBackground(new java.awt.Color(77, 69, 51));
        p01.setPreferredSize(new java.awt.Dimension(70, 70));

        btn01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_horse.png"))); // NOI18N

        javax.swing.GroupLayout p01Layout = new javax.swing.GroupLayout(p01);
        p01.setLayout(p01Layout);
        p01Layout.setHorizontalGroup(
            p01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn01, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p01Layout.setVerticalGroup(
            p01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn01, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p02.setBackground(new java.awt.Color(245, 244, 239));
        p02.setPreferredSize(new java.awt.Dimension(70, 70));

        btn02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_bishop.png"))); // NOI18N

        javax.swing.GroupLayout p02Layout = new javax.swing.GroupLayout(p02);
        p02.setLayout(p02Layout);
        p02Layout.setHorizontalGroup(
            p02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn02, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p02Layout.setVerticalGroup(
            p02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn02, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p03.setBackground(new java.awt.Color(77, 69, 51));
        p03.setPreferredSize(new java.awt.Dimension(70, 70));

        btn03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_queen.png"))); // NOI18N

        javax.swing.GroupLayout p03Layout = new javax.swing.GroupLayout(p03);
        p03.setLayout(p03Layout);
        p03Layout.setHorizontalGroup(
            p03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn03, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p03Layout.setVerticalGroup(
            p03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn03, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p04.setBackground(new java.awt.Color(245, 244, 239));
        p04.setPreferredSize(new java.awt.Dimension(70, 70));

        btn04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_king.png"))); // NOI18N

        javax.swing.GroupLayout p04Layout = new javax.swing.GroupLayout(p04);
        p04.setLayout(p04Layout);
        p04Layout.setHorizontalGroup(
            p04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn04, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p04Layout.setVerticalGroup(
            p04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn04, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p05.setBackground(new java.awt.Color(77, 69, 51));
        p05.setPreferredSize(new java.awt.Dimension(70, 70));

        btn05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_bishop.png"))); // NOI18N

        javax.swing.GroupLayout p05Layout = new javax.swing.GroupLayout(p05);
        p05.setLayout(p05Layout);
        p05Layout.setHorizontalGroup(
            p05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn05, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p05Layout.setVerticalGroup(
            p05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn05, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p06.setBackground(new java.awt.Color(245, 244, 239));
        p06.setPreferredSize(new java.awt.Dimension(70, 70));

        btn06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_horse.png"))); // NOI18N

        javax.swing.GroupLayout p06Layout = new javax.swing.GroupLayout(p06);
        p06.setLayout(p06Layout);
        p06Layout.setHorizontalGroup(
            p06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn06, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p06Layout.setVerticalGroup(
            p06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn06, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p07.setBackground(new java.awt.Color(77, 69, 51));
        p07.setPreferredSize(new java.awt.Dimension(70, 70));

        btn07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_tower.png"))); // NOI18N

        javax.swing.GroupLayout p07Layout = new javax.swing.GroupLayout(p07);
        p07.setLayout(p07Layout);
        p07Layout.setHorizontalGroup(
            p07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn07, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p07Layout.setVerticalGroup(
            p07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn07, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p10.setBackground(new java.awt.Color(77, 69, 51));
        p10.setPreferredSize(new java.awt.Dimension(70, 70));

        btn10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p10Layout = new javax.swing.GroupLayout(p10);
        p10.setLayout(p10Layout);
        p10Layout.setHorizontalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p10Layout.setVerticalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p11.setBackground(new java.awt.Color(245, 244, 239));
        p11.setPreferredSize(new java.awt.Dimension(70, 70));

        btn11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p12.setBackground(new java.awt.Color(77, 69, 51));
        p12.setPreferredSize(new java.awt.Dimension(70, 70));

        btn12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p12Layout = new javax.swing.GroupLayout(p12);
        p12.setLayout(p12Layout);
        p12Layout.setHorizontalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p12Layout.setVerticalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p13.setBackground(new java.awt.Color(245, 244, 239));
        p13.setPreferredSize(new java.awt.Dimension(70, 70));

        btn13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p13Layout = new javax.swing.GroupLayout(p13);
        p13.setLayout(p13Layout);
        p13Layout.setHorizontalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p13Layout.setVerticalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p14.setBackground(new java.awt.Color(77, 69, 51));
        p14.setPreferredSize(new java.awt.Dimension(70, 70));

        btn14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p14Layout = new javax.swing.GroupLayout(p14);
        p14.setLayout(p14Layout);
        p14Layout.setHorizontalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn14, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p14Layout.setVerticalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn14, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p15.setBackground(new java.awt.Color(245, 244, 239));
        p15.setPreferredSize(new java.awt.Dimension(70, 70));

        btn15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p15Layout = new javax.swing.GroupLayout(p15);
        p15.setLayout(p15Layout);
        p15Layout.setHorizontalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn15, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p15Layout.setVerticalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn15, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p16.setBackground(new java.awt.Color(77, 69, 51));
        p16.setPreferredSize(new java.awt.Dimension(70, 70));

        btn16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p16Layout = new javax.swing.GroupLayout(p16);
        p16.setLayout(p16Layout);
        p16Layout.setHorizontalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn16, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p16Layout.setVerticalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn16, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p17.setBackground(new java.awt.Color(245, 244, 239));
        p17.setPreferredSize(new java.awt.Dimension(70, 70));

        btn17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png"))); // NOI18N

        javax.swing.GroupLayout p17Layout = new javax.swing.GroupLayout(p17);
        p17.setLayout(p17Layout);
        p17Layout.setHorizontalGroup(
            p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn17, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p17Layout.setVerticalGroup(
            p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn17, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p30.setBackground(new java.awt.Color(77, 69, 51));
        p30.setPreferredSize(new java.awt.Dimension(70, 70));

        btn30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p30Layout = new javax.swing.GroupLayout(p30);
        p30.setLayout(p30Layout);
        p30Layout.setHorizontalGroup(
            p30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn30, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p30Layout.setVerticalGroup(
            p30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn30, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p31.setBackground(new java.awt.Color(245, 244, 239));
        p31.setPreferredSize(new java.awt.Dimension(70, 70));

        btn31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p31Layout = new javax.swing.GroupLayout(p31);
        p31.setLayout(p31Layout);
        p31Layout.setHorizontalGroup(
            p31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn31, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p31Layout.setVerticalGroup(
            p31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn31, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p32.setBackground(new java.awt.Color(77, 69, 51));
        p32.setPreferredSize(new java.awt.Dimension(70, 70));

        btn32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p32Layout = new javax.swing.GroupLayout(p32);
        p32.setLayout(p32Layout);
        p32Layout.setHorizontalGroup(
            p32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn32, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p32Layout.setVerticalGroup(
            p32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn32, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p33.setBackground(new java.awt.Color(245, 244, 239));
        p33.setPreferredSize(new java.awt.Dimension(70, 70));

        btn33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p33Layout = new javax.swing.GroupLayout(p33);
        p33.setLayout(p33Layout);
        p33Layout.setHorizontalGroup(
            p33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn33, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p33Layout.setVerticalGroup(
            p33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn33, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p34.setBackground(new java.awt.Color(77, 69, 51));
        p34.setPreferredSize(new java.awt.Dimension(70, 70));

        btn34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p34Layout = new javax.swing.GroupLayout(p34);
        p34.setLayout(p34Layout);
        p34Layout.setHorizontalGroup(
            p34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn34, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p34Layout.setVerticalGroup(
            p34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn34, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p35.setBackground(new java.awt.Color(245, 244, 239));
        p35.setPreferredSize(new java.awt.Dimension(70, 70));

        btn35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p35Layout = new javax.swing.GroupLayout(p35);
        p35.setLayout(p35Layout);
        p35Layout.setHorizontalGroup(
            p35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn35, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p35Layout.setVerticalGroup(
            p35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn35, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p36.setBackground(new java.awt.Color(77, 69, 51));
        p36.setPreferredSize(new java.awt.Dimension(70, 70));

        btn36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p36Layout = new javax.swing.GroupLayout(p36);
        p36.setLayout(p36Layout);
        p36Layout.setHorizontalGroup(
            p36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn36, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p36Layout.setVerticalGroup(
            p36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn36, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p37.setBackground(new java.awt.Color(245, 244, 239));
        p37.setPreferredSize(new java.awt.Dimension(70, 70));

        btn37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p37Layout = new javax.swing.GroupLayout(p37);
        p37.setLayout(p37Layout);
        p37Layout.setHorizontalGroup(
            p37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn37, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p37Layout.setVerticalGroup(
            p37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn37, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p27.setBackground(new java.awt.Color(77, 69, 51));
        p27.setPreferredSize(new java.awt.Dimension(70, 70));

        btn27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p27Layout = new javax.swing.GroupLayout(p27);
        p27.setLayout(p27Layout);
        p27Layout.setHorizontalGroup(
            p27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn27, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p27Layout.setVerticalGroup(
            p27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn27, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p26.setBackground(new java.awt.Color(245, 244, 239));
        p26.setPreferredSize(new java.awt.Dimension(70, 70));

        btn26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p26Layout = new javax.swing.GroupLayout(p26);
        p26.setLayout(p26Layout);
        p26Layout.setHorizontalGroup(
            p26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn26, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p26Layout.setVerticalGroup(
            p26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn26, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p25.setBackground(new java.awt.Color(77, 69, 51));
        p25.setPreferredSize(new java.awt.Dimension(70, 70));

        btn25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p25Layout = new javax.swing.GroupLayout(p25);
        p25.setLayout(p25Layout);
        p25Layout.setHorizontalGroup(
            p25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn25, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p25Layout.setVerticalGroup(
            p25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn25, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p24.setBackground(new java.awt.Color(245, 244, 239));
        p24.setPreferredSize(new java.awt.Dimension(70, 70));

        btn24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p24Layout = new javax.swing.GroupLayout(p24);
        p24.setLayout(p24Layout);
        p24Layout.setHorizontalGroup(
            p24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn24, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p24Layout.setVerticalGroup(
            p24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn24, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p23.setBackground(new java.awt.Color(77, 69, 51));
        p23.setPreferredSize(new java.awt.Dimension(70, 70));

        btn23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p23Layout = new javax.swing.GroupLayout(p23);
        p23.setLayout(p23Layout);
        p23Layout.setHorizontalGroup(
            p23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn23, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p23Layout.setVerticalGroup(
            p23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn23, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p22.setBackground(new java.awt.Color(245, 244, 239));
        p22.setPreferredSize(new java.awt.Dimension(70, 70));

        btn22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p22Layout = new javax.swing.GroupLayout(p22);
        p22.setLayout(p22Layout);
        p22Layout.setHorizontalGroup(
            p22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn22, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p22Layout.setVerticalGroup(
            p22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn22, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p21.setBackground(new java.awt.Color(77, 69, 51));
        p21.setPreferredSize(new java.awt.Dimension(70, 70));

        btn21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p21Layout = new javax.swing.GroupLayout(p21);
        p21.setLayout(p21Layout);
        p21Layout.setHorizontalGroup(
            p21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn21, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p21Layout.setVerticalGroup(
            p21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn21, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p20.setBackground(new java.awt.Color(245, 244, 239));
        p20.setPreferredSize(new java.awt.Dimension(70, 70));

        btn20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p20Layout = new javax.swing.GroupLayout(p20);
        p20.setLayout(p20Layout);
        p20Layout.setHorizontalGroup(
            p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn20, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p20Layout.setVerticalGroup(
            p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn20, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p57.setBackground(new java.awt.Color(245, 244, 239));
        p57.setPreferredSize(new java.awt.Dimension(70, 70));

        btn57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p57Layout = new javax.swing.GroupLayout(p57);
        p57.setLayout(p57Layout);
        p57Layout.setHorizontalGroup(
            p57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn57, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p57Layout.setVerticalGroup(
            p57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn57, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p47.setBackground(new java.awt.Color(77, 69, 51));
        p47.setPreferredSize(new java.awt.Dimension(70, 70));

        btn47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p47Layout = new javax.swing.GroupLayout(p47);
        p47.setLayout(p47Layout);
        p47Layout.setHorizontalGroup(
            p47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn47, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p47Layout.setVerticalGroup(
            p47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn47, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p46.setBackground(new java.awt.Color(245, 244, 239));
        p46.setPreferredSize(new java.awt.Dimension(70, 70));

        btn46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p46Layout = new javax.swing.GroupLayout(p46);
        p46.setLayout(p46Layout);
        p46Layout.setHorizontalGroup(
            p46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn46, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p46Layout.setVerticalGroup(
            p46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn46, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p45.setBackground(new java.awt.Color(77, 69, 51));
        p45.setPreferredSize(new java.awt.Dimension(70, 70));

        btn45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p45Layout = new javax.swing.GroupLayout(p45);
        p45.setLayout(p45Layout);
        p45Layout.setHorizontalGroup(
            p45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn45, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p45Layout.setVerticalGroup(
            p45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn45, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p44.setBackground(new java.awt.Color(245, 244, 239));
        p44.setPreferredSize(new java.awt.Dimension(70, 70));

        btn44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p44Layout = new javax.swing.GroupLayout(p44);
        p44.setLayout(p44Layout);
        p44Layout.setHorizontalGroup(
            p44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn44, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p44Layout.setVerticalGroup(
            p44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn44, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p43.setBackground(new java.awt.Color(77, 69, 51));
        p43.setPreferredSize(new java.awt.Dimension(70, 70));

        btn43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p43Layout = new javax.swing.GroupLayout(p43);
        p43.setLayout(p43Layout);
        p43Layout.setHorizontalGroup(
            p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn43, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p43Layout.setVerticalGroup(
            p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn43, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p42.setBackground(new java.awt.Color(245, 244, 239));
        p42.setPreferredSize(new java.awt.Dimension(70, 70));

        btn42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p42Layout = new javax.swing.GroupLayout(p42);
        p42.setLayout(p42Layout);
        p42Layout.setHorizontalGroup(
            p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn42, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p42Layout.setVerticalGroup(
            p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn42, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p41.setBackground(new java.awt.Color(77, 69, 51));
        p41.setPreferredSize(new java.awt.Dimension(70, 70));

        btn41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p41Layout = new javax.swing.GroupLayout(p41);
        p41.setLayout(p41Layout);
        p41Layout.setHorizontalGroup(
            p41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn41, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p41Layout.setVerticalGroup(
            p41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn41, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p40.setBackground(new java.awt.Color(245, 244, 239));
        p40.setPreferredSize(new java.awt.Dimension(70, 70));

        btn40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p40Layout = new javax.swing.GroupLayout(p40);
        p40.setLayout(p40Layout);
        p40Layout.setHorizontalGroup(
            p40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn40, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p40Layout.setVerticalGroup(
            p40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn40, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p50.setBackground(new java.awt.Color(77, 69, 51));
        p50.setPreferredSize(new java.awt.Dimension(70, 70));

        btn50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p50Layout = new javax.swing.GroupLayout(p50);
        p50.setLayout(p50Layout);
        p50Layout.setHorizontalGroup(
            p50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn50, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p50Layout.setVerticalGroup(
            p50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn50, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p51.setBackground(new java.awt.Color(245, 244, 239));
        p51.setPreferredSize(new java.awt.Dimension(70, 70));

        btn51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p51Layout = new javax.swing.GroupLayout(p51);
        p51.setLayout(p51Layout);
        p51Layout.setHorizontalGroup(
            p51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn51, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p51Layout.setVerticalGroup(
            p51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn51, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p52.setBackground(new java.awt.Color(77, 69, 51));
        p52.setPreferredSize(new java.awt.Dimension(70, 70));

        btn52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p52Layout = new javax.swing.GroupLayout(p52);
        p52.setLayout(p52Layout);
        p52Layout.setHorizontalGroup(
            p52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn52, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p52Layout.setVerticalGroup(
            p52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn52, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p53.setBackground(new java.awt.Color(245, 244, 239));
        p53.setPreferredSize(new java.awt.Dimension(70, 70));

        btn53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p53Layout = new javax.swing.GroupLayout(p53);
        p53.setLayout(p53Layout);
        p53Layout.setHorizontalGroup(
            p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn53, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p53Layout.setVerticalGroup(
            p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn53, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p54.setBackground(new java.awt.Color(77, 69, 51));
        p54.setPreferredSize(new java.awt.Dimension(70, 70));

        btn54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p54Layout = new javax.swing.GroupLayout(p54);
        p54.setLayout(p54Layout);
        p54Layout.setHorizontalGroup(
            p54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn54, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p54Layout.setVerticalGroup(
            p54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn54, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p55.setBackground(new java.awt.Color(245, 244, 239));
        p55.setPreferredSize(new java.awt.Dimension(70, 70));

        btn55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p55Layout = new javax.swing.GroupLayout(p55);
        p55.setLayout(p55Layout);
        p55Layout.setHorizontalGroup(
            p55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn55, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p55Layout.setVerticalGroup(
            p55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn55, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p56.setBackground(new java.awt.Color(77, 69, 51));
        p56.setPreferredSize(new java.awt.Dimension(70, 70));

        btn56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p56Layout = new javax.swing.GroupLayout(p56);
        p56.setLayout(p56Layout);
        p56Layout.setHorizontalGroup(
            p56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn56, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p56Layout.setVerticalGroup(
            p56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn56, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p77.setBackground(new java.awt.Color(245, 244, 239));
        p77.setPreferredSize(new java.awt.Dimension(70, 70));

        btn77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_tower.png"))); // NOI18N

        javax.swing.GroupLayout p77Layout = new javax.swing.GroupLayout(p77);
        p77.setLayout(p77Layout);
        p77Layout.setHorizontalGroup(
            p77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn77, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p77Layout.setVerticalGroup(
            p77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn77, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p67.setBackground(new java.awt.Color(77, 69, 51));
        p67.setPreferredSize(new java.awt.Dimension(70, 70));

        btn67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p67Layout = new javax.swing.GroupLayout(p67);
        p67.setLayout(p67Layout);
        p67Layout.setHorizontalGroup(
            p67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn67, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p67Layout.setVerticalGroup(
            p67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn67, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p66.setBackground(new java.awt.Color(245, 244, 239));
        p66.setPreferredSize(new java.awt.Dimension(70, 70));

        btn66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p66Layout = new javax.swing.GroupLayout(p66);
        p66.setLayout(p66Layout);
        p66Layout.setHorizontalGroup(
            p66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn66, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p66Layout.setVerticalGroup(
            p66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn66, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p65.setBackground(new java.awt.Color(77, 69, 51));
        p65.setPreferredSize(new java.awt.Dimension(70, 70));

        btn65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p65Layout = new javax.swing.GroupLayout(p65);
        p65.setLayout(p65Layout);
        p65Layout.setHorizontalGroup(
            p65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn65, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p65Layout.setVerticalGroup(
            p65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn65, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p64.setBackground(new java.awt.Color(245, 244, 239));
        p64.setPreferredSize(new java.awt.Dimension(70, 70));

        btn64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p64Layout = new javax.swing.GroupLayout(p64);
        p64.setLayout(p64Layout);
        p64Layout.setHorizontalGroup(
            p64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn64, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p64Layout.setVerticalGroup(
            p64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn64, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p63.setBackground(new java.awt.Color(77, 69, 51));
        p63.setPreferredSize(new java.awt.Dimension(70, 70));

        btn63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p63Layout = new javax.swing.GroupLayout(p63);
        p63.setLayout(p63Layout);
        p63Layout.setHorizontalGroup(
            p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn63, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p63Layout.setVerticalGroup(
            p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn63, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p62.setBackground(new java.awt.Color(245, 244, 239));
        p62.setPreferredSize(new java.awt.Dimension(70, 70));

        btn62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p62Layout = new javax.swing.GroupLayout(p62);
        p62.setLayout(p62Layout);
        p62Layout.setHorizontalGroup(
            p62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn62, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p62Layout.setVerticalGroup(
            p62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn62, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p61.setBackground(new java.awt.Color(77, 69, 51));
        p61.setPreferredSize(new java.awt.Dimension(70, 70));

        btn61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p61Layout = new javax.swing.GroupLayout(p61);
        p61.setLayout(p61Layout);
        p61Layout.setHorizontalGroup(
            p61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn61, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p61Layout.setVerticalGroup(
            p61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn61, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p60.setBackground(new java.awt.Color(245, 244, 239));
        p60.setPreferredSize(new java.awt.Dimension(70, 70));

        btn60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_peao.png"))); // NOI18N

        javax.swing.GroupLayout p60Layout = new javax.swing.GroupLayout(p60);
        p60.setLayout(p60Layout);
        p60Layout.setHorizontalGroup(
            p60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn60, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p60Layout.setVerticalGroup(
            p60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn60, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p70.setBackground(new java.awt.Color(77, 69, 51));
        p70.setPreferredSize(new java.awt.Dimension(70, 70));

        btn70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_tower.png"))); // NOI18N

        javax.swing.GroupLayout p70Layout = new javax.swing.GroupLayout(p70);
        p70.setLayout(p70Layout);
        p70Layout.setHorizontalGroup(
            p70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn70, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p70Layout.setVerticalGroup(
            p70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn70, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p71.setBackground(new java.awt.Color(245, 244, 239));
        p71.setPreferredSize(new java.awt.Dimension(70, 70));

        btn71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_horse.png"))); // NOI18N

        javax.swing.GroupLayout p71Layout = new javax.swing.GroupLayout(p71);
        p71.setLayout(p71Layout);
        p71Layout.setHorizontalGroup(
            p71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn71, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p71Layout.setVerticalGroup(
            p71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn71, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p72.setBackground(new java.awt.Color(77, 69, 51));
        p72.setPreferredSize(new java.awt.Dimension(70, 70));

        btn72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_bishop.png"))); // NOI18N

        javax.swing.GroupLayout p72Layout = new javax.swing.GroupLayout(p72);
        p72.setLayout(p72Layout);
        p72Layout.setHorizontalGroup(
            p72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn72, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p72Layout.setVerticalGroup(
            p72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn72, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p73.setBackground(new java.awt.Color(245, 244, 239));
        p73.setPreferredSize(new java.awt.Dimension(70, 70));

        btn73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_queen.png"))); // NOI18N

        javax.swing.GroupLayout p73Layout = new javax.swing.GroupLayout(p73);
        p73.setLayout(p73Layout);
        p73Layout.setHorizontalGroup(
            p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn73, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p73Layout.setVerticalGroup(
            p73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn73, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p74.setBackground(new java.awt.Color(77, 69, 51));
        p74.setPreferredSize(new java.awt.Dimension(70, 70));

        btn74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_king.png"))); // NOI18N

        javax.swing.GroupLayout p74Layout = new javax.swing.GroupLayout(p74);
        p74.setLayout(p74Layout);
        p74Layout.setHorizontalGroup(
            p74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn74, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p74Layout.setVerticalGroup(
            p74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn74, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p75.setBackground(new java.awt.Color(245, 244, 239));
        p75.setPreferredSize(new java.awt.Dimension(70, 70));

        btn75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_bishop.png"))); // NOI18N

        javax.swing.GroupLayout p75Layout = new javax.swing.GroupLayout(p75);
        p75.setLayout(p75Layout);
        p75Layout.setHorizontalGroup(
            p75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn75, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p75Layout.setVerticalGroup(
            p75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn75, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        p76.setBackground(new java.awt.Color(77, 69, 51));
        p76.setPreferredSize(new java.awt.Dimension(70, 70));

        btn76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/w_horse.png"))); // NOI18N

        javax.swing.GroupLayout p76Layout = new javax.swing.GroupLayout(p76);
        p76.setLayout(p76Layout);
        p76Layout.setHorizontalGroup(
            p76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn76, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        p76Layout.setVerticalGroup(
            p76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn76, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgBoardLayout = new javax.swing.GroupLayout(bgBoard);
        bgBoard.setLayout(bgBoardLayout);
        bgBoardLayout.setHorizontalGroup(
            bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBoardLayout.createSequentialGroup()
                .addComponent(p00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgBoardLayout.createSequentialGroup()
                .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgBoardLayout.createSequentialGroup()
                .addComponent(p40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgBoardLayout.createSequentialGroup()
                .addComponent(p60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgBoardLayout.createSequentialGroup()
                .addComponent(p70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(p77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgBoardLayout.createSequentialGroup()
                    .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgBoardLayout.createSequentialGroup()
                    .addComponent(p30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgBoardLayout.createSequentialGroup()
                    .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(p57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        bgBoardLayout.setVerticalGroup(
            bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBoardLayout.createSequentialGroup()
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p73, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgGameLayout = new javax.swing.GroupLayout(bgGame);
        bgGame.setLayout(bgGameLayout);
        bgGameLayout.setHorizontalGroup(
            bgGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgGameLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(bgBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        bgGameLayout.setVerticalGroup(
            bgGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgGameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bgBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boardGame().setVisible(true);
            }
        });
    }
    
    
    //Set visual board Game
    public void setVisualPos(int chessPiece, int x, int y){
       //btn17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/assets/b_peao.png")));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgBoard;
    private javax.swing.JPanel bgGame;
    private javax.swing.JLabel btn00;
    private javax.swing.JLabel btn01;
    private javax.swing.JLabel btn02;
    private javax.swing.JLabel btn03;
    private javax.swing.JLabel btn04;
    private javax.swing.JLabel btn05;
    private javax.swing.JLabel btn06;
    private javax.swing.JLabel btn07;
    private javax.swing.JLabel btn10;
    private javax.swing.JLabel btn11;
    private javax.swing.JLabel btn12;
    private javax.swing.JLabel btn13;
    private javax.swing.JLabel btn14;
    private javax.swing.JLabel btn15;
    private javax.swing.JLabel btn16;
    private javax.swing.JLabel btn17;
    private javax.swing.JLabel btn20;
    private javax.swing.JLabel btn21;
    private javax.swing.JLabel btn22;
    private javax.swing.JLabel btn23;
    private javax.swing.JLabel btn24;
    private javax.swing.JLabel btn25;
    private javax.swing.JLabel btn26;
    private javax.swing.JLabel btn27;
    private javax.swing.JLabel btn30;
    private javax.swing.JLabel btn31;
    private javax.swing.JLabel btn32;
    private javax.swing.JLabel btn33;
    private javax.swing.JLabel btn34;
    private javax.swing.JLabel btn35;
    private javax.swing.JLabel btn36;
    private javax.swing.JLabel btn37;
    private javax.swing.JLabel btn40;
    private javax.swing.JLabel btn41;
    private javax.swing.JLabel btn42;
    private javax.swing.JLabel btn43;
    private javax.swing.JLabel btn44;
    private javax.swing.JLabel btn45;
    private javax.swing.JLabel btn46;
    private javax.swing.JLabel btn47;
    private javax.swing.JLabel btn50;
    private javax.swing.JLabel btn51;
    private javax.swing.JLabel btn52;
    private javax.swing.JLabel btn53;
    private javax.swing.JLabel btn54;
    private javax.swing.JLabel btn55;
    private javax.swing.JLabel btn56;
    private javax.swing.JLabel btn57;
    private javax.swing.JLabel btn60;
    private javax.swing.JLabel btn61;
    private javax.swing.JLabel btn62;
    private javax.swing.JLabel btn63;
    private javax.swing.JLabel btn64;
    private javax.swing.JLabel btn65;
    private javax.swing.JLabel btn66;
    private javax.swing.JLabel btn67;
    private javax.swing.JLabel btn70;
    private javax.swing.JLabel btn71;
    private javax.swing.JLabel btn72;
    private javax.swing.JLabel btn73;
    private javax.swing.JLabel btn74;
    private javax.swing.JLabel btn75;
    private javax.swing.JLabel btn76;
    private javax.swing.JLabel btn77;
    private javax.swing.JPanel p00;
    private javax.swing.JPanel p01;
    private javax.swing.JPanel p02;
    private javax.swing.JPanel p03;
    private javax.swing.JPanel p04;
    private javax.swing.JPanel p05;
    private javax.swing.JPanel p06;
    private javax.swing.JPanel p07;
    private javax.swing.JPanel p10;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p12;
    private javax.swing.JPanel p13;
    private javax.swing.JPanel p14;
    private javax.swing.JPanel p15;
    private javax.swing.JPanel p16;
    private javax.swing.JPanel p17;
    private javax.swing.JPanel p20;
    private javax.swing.JPanel p21;
    private javax.swing.JPanel p22;
    private javax.swing.JPanel p23;
    private javax.swing.JPanel p24;
    private javax.swing.JPanel p25;
    private javax.swing.JPanel p26;
    private javax.swing.JPanel p27;
    private javax.swing.JPanel p30;
    private javax.swing.JPanel p31;
    private javax.swing.JPanel p32;
    private javax.swing.JPanel p33;
    private javax.swing.JPanel p34;
    private javax.swing.JPanel p35;
    private javax.swing.JPanel p36;
    private javax.swing.JPanel p37;
    private javax.swing.JPanel p40;
    private javax.swing.JPanel p41;
    private javax.swing.JPanel p42;
    private javax.swing.JPanel p43;
    private javax.swing.JPanel p44;
    private javax.swing.JPanel p45;
    private javax.swing.JPanel p46;
    private javax.swing.JPanel p47;
    private javax.swing.JPanel p50;
    private javax.swing.JPanel p51;
    private javax.swing.JPanel p52;
    private javax.swing.JPanel p53;
    private javax.swing.JPanel p54;
    private javax.swing.JPanel p55;
    private javax.swing.JPanel p56;
    private javax.swing.JPanel p57;
    private javax.swing.JPanel p60;
    private javax.swing.JPanel p61;
    private javax.swing.JPanel p62;
    private javax.swing.JPanel p63;
    private javax.swing.JPanel p64;
    private javax.swing.JPanel p65;
    private javax.swing.JPanel p66;
    private javax.swing.JPanel p67;
    private javax.swing.JPanel p70;
    private javax.swing.JPanel p71;
    private javax.swing.JPanel p72;
    private javax.swing.JPanel p73;
    private javax.swing.JPanel p74;
    private javax.swing.JPanel p75;
    private javax.swing.JPanel p76;
    private javax.swing.JPanel p77;
    // End of variables declaration//GEN-END:variables
}
